# Generated by Django 3.0.2 on 2020-01-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pub_date',
        ),
    ]
